### ISSUE TITLE
Implementação da interface web

### ISSUE THREAD

**Issue by fboldt** [fboldt/scraper#1]
- [x] Página inicial "bonitinha" com CSS.
- [x] Formulário para entrar com a URL "https://en.wikipedia.org/wiki/List_of_dog_breeds". Este formulário envia essa URL para uma página que mostrará o progresso dos downloads das imagens.
- [ ] Implementar a página que mostra o progresso dos downloads das imagens.

**Comment by luddias** [comment]
ok!
