### ISSUE TITLE
Buscar alguma maneira de "identar" o arquivo json que agora foi reestruturado.

### ISSUE THREAD

**Issue by mvmfaria** [fboldt/scraper#5]
O que precisamos é basicamente fazer o que esse site faz: [https://jsononline.net/pt/json-formatter](url). De forma geral, ele pega um arquivo .json que está todo aglomerado e estrutura ele de maneira que seja visualmente mais fácil de compreender.

**Comment by artcarvalho** [comment]
Adicionei o arquivo "Identa_json.json" na pasta public, ele lê o arquivo json e cria outro estruturado, dá pra fazer ele substituir o arquivo list.json direto caso necessário.

obs: caso o arquivo não possa ficar na pasta public me avise.

**Comment by mvmfaria** [comment]
Aparentemente precisava apenas colocar os parâmetros na função (`stringify()`) que gera o json, né?

Eu fiz a alteração direta no arquivo "crawler.js" conforme você sugeriu. Dessa maneira, a gente não precisa manter esse arquivo apenas para formatar o json.

Valeu!!!
